- defaults:
    link:
      relink: true
      relative: true

- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.bash_profile: bash/bash_profile
    ~/.bashrc: bash/bashrc
    ~/.gitconfig: gitconfig
    ~/.inputrc: inputrc
    ~/.liquidpromptrc: bash/liquidpromptrc
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim
    ~/.vimrc: vimrc

- shell:
  -
    command: git submodule update --init --recursive
    description: Installing submodules
  -
    command: mkdir -p -m 0700 ~/tmp/vim
    description: Create local tmp dir
  -
    command: >
      curl -fLo ~/.dotfiles/vim/autoload/plug.vim --create-dirs
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    description: Downloading vim-plug
  -
    command: ~/.dotfiles/fzf/install --bin
    description: Downloading fzf binary
