#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR=".dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

if [[ "${1:-}" != *-h* ]]; then
	# Some config files needs to be made before dotbot can install them.
	PATH="$PATH:$HOME/.local/bin" make
fi

git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
