#!/bin/bash
# vim: et ts=4 sw=4
set -euo pipefail

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(basename "$BASEDIR")"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"$HOME/.config"}"
VIMRUNTIME="$XDG_CONFIG_HOME/nvim"
VIM_PLUGIN_DIR="$VIMRUNTIME/pack/git/start"

COLOR_CYAN="0;36"
COLOR_GREEN="0;32"
COLOR_RED="0;31"
COLOR_YELLOW="0;33"
COLOR_RESET="0"

username="$(id -un)"
verbose=""
vflag=""
clone_git_repos=1

usage() {
	cat <<-EOF
	Setup dotfiles.

	environment vars:
		DOTFILES_ENABLE_FD
		DOTFILES_ENABLE_GIT_PULL
		DOTFILES_FZF_BASH_BINDINGS (path)

	  --no-git          don't clone git dependencies
	  -v, --verbose
	EOF
	exit
}

log() {
    echo -e "\e[${COLOR_CYAN}mINFO: ""$@""\e[0m" >&2
}

runlog() {
    echo -e "\e[${COLOR_GREEN}mrun: ""$@""\e[0m" >&2
    $@
}

error() {
    echo -e "\e[${COLOR_RED}mERROR: ""$@""\e[0m" >&2
    exit 1
}

debug() {
    [ -n "$verbose" ] && echo -e "\e[${COLOR_YELLOW}mDEBUG: ""$@""\e[0m" >&2
    return 0
}

# usage: symlink_file [-f] target_within_dotfiles [link_name]
symlink_file() {
    local target link force
    if [ "$1" == "-f" ]; then
        force=1
        shift
    fi
    target="$DOTFILES_DIR/$1"
    link="${2:-.$(basename $1)}"
    debug "install symlink to $1"
    if [ -z "${force:-}" ] && [ -e "$link" ] && ! [ -h "$link" ]; then
        log "will not overwrite normal file: $link"
    else
        ln -srf $vflag $target $link
    fi
}

orig_args=( "$@" )
while [ -n "${1:-}" ]; do
    case "$1" in
        --no-git)           clone_git_repos=0; shift; break ;;
        -v|--verbose)       verbose=1; shift; break ;;
        -h|--help)          usage ;;
        -*)
            echo "unknown option: $1" >&2
            usage
            ;;
    esac
done
vflag="${verbose:+-v}"

debug "Ensure things run from home dir"
cd

debug "Setup dotfiles predictable link"
rm -f .dotfiles && ln -s "$DOTFILES_DIR" .dotfiles

if [ $clone_git_repos -eq 1 ]; then
    log "download git dependencies..."
    export VIM_PLUGIN_DIR  # for clone_git
    mkdir -p $vflag $VIM_PLUGIN_DIR
    . $DOTFILES_DIR/clone_git.sh
fi

#
# bash
#
symlink_file -f bashrc

debug "Create .bashrc.d and link files, to enable mixing in local files too"
mkdir $vflag -p .bashrc.d
for rcfile in $DOTFILES_DIR/bashrc.d/*; do
    link=".bashrc.d/$(basename $rcfile)"
    if [ -z "${force:-}" ] && [ -e "$link" ] && ! [ -h "$link" ]; then
        log "will not overwrite normal file: $link"
        continue
    fi
    ln -sfr $vflag $rcfile .bashrc.d/
done
# end bash

#
# tmux
#
# Older tmux versions don't use XDG_CONFIG_HOME, therefor keep config at ~/.tmux.conf
symlink_file tmux/tmux.conf

mkdir -p $vflag $XDG_CONFIG_HOME/tmux{,-buffers,-sessions}
if ! [ -e $XDG_CONFIG_HOME/tmux-sessions/index ]; then
    sed -e "s/%USERNAME%/$username/" $DOTFILES_DIR/tmux/sessions-index.sample > $XDG_CONFIG_HOME/tmux-sessions/index
fi
# end tmux

#
# git
#
debug "setup git"
symlink_file gitconfig
if ! [ -e .gitconfig_local ]; then
    cat > .gitconfig_local <<EOF
[user]
	name = "$(getent passwd $username | cut -d: -f5)"
	#email = "22745764+sjoegren@users.noreply.github.com"
EOF
    log "wrote new .gitconfig_local - please update with email"
fi
# end git

#
# neovim
#
debug "setup neovim"
symlink_file vim/init.lua $VIMRUNTIME/init.lua
debug "generate any missing helptags for vim plugins"
for docpath in $(find $VIM_PLUGIN_DIR -type d -name doc); do
    if ! [ -e "$docpath/tags" ]; then
        log "generate vim helptags for $docpath"
        nvim -u NONE -c "helptags $docpath" -c q
        sleep 0.1
    else
        debug "$docpath already has tags"
    fi
done

mkdir -p $vflag $VIMRUNTIME/after/ftplugin
for f in $DOTFILES_DIR/vim/ftplugin/*.vim; do
    ln -srf $vflag "$f" "$VIMRUNTIME/after/ftplugin/$(basename $f)"
done
# end neovim

symlink_file liquidpromptrc
symlink_file inputrc
symlink_file pdbrc

mkdir -p $vflag tmp
