#!/bin/bash
# vim: et ts=4 sw=4
set -euo pipefail

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(basename "$BASEDIR")"

COLOR_CYAN="0;36"
COLOR_GREEN="0;32"
COLOR_RED="0;31"
COLOR_YELLOW="0;33"
COLOR_RESET="0"

verbose=""
vflag=""
clone_git_repos=1

usage() {
	cat <<-EOF
	Setup dotfiles.

	environment vars:
		DOTFILES_ENABLE_FD
		DOTFILES_ENABLE_GIT_PULL
		DOTFILES_FZF_BASH_BINDINGS (path)

	  --no-git          don't clone git dependencies
	  -v, --verbose
	EOF
	exit
}

log() {
    echo -e "\e[${COLOR_CYAN}mINFO: ""$@""\e[0m" >&2
}

runlog() {
    echo -e "\e[${COLOR_GREEN}mrun: ""$@""\e[0m" >&2
    $@
}

error() {
    echo -e "\e[${COLOR_RED}mERROR: ""$@""\e[0m" >&2
    exit 1
}

debug() {
    [ -n "$verbose" ] && echo -e "\e[${COLOR_YELLOW}mDEBUG: ""$@""\e[0m" >&2
    return 0
}

# usage: symlink_file [-f] target_within_dotfiles [link_name]
symlink_file() {
    local target link force
    if [ "$1" == "-f" ]; then
        force=1
        shift
    fi
    target="$DOTFILES_DIR/$1"
    link="${2:-.$1}"
    # log "Create link to $1"
    if [ -z "${force:-}" ] && [ -e "$link" ] && ! [ -h "$link" ]; then
        log "will not overwrite normal file: $link"
    else
        ln -sf $vflag $target $link
    fi
}

orig_args=( "$@" )
while [ -n "${1:-}" ]; do
    case "$1" in
        --no-git)           clone_git_repos=0; shift; break ;;
        -v|--verbose)       verbose=1; shift; break ;;
        -h|--help)          usage ;;
        -*)
            echo "unknown option: $1" >&2
            usage
            ;;
    esac
done
vflag="${verbose:+-v}"

debug "Ensure things run from home dir"
cd

debug "Setup dotfiles predictable link"
rm -f .dotfiles && ln -s "$DOTFILES_DIR" .dotfiles

if [ $clone_git_repos -eq 1 ]; then
    . $DOTFILES_DIR/clone_git.sh
fi

log "setup bash files..."
symlink_file -f bashrc

# Create .bashrc.d and link files, to enable mixing in local files too.
mkdir $vflag -p .bashrc.d
for rcfile in $DOTFILES_DIR/bashrc.d/*; do
    link=".bashrc.d/$(basename $rcfile)"
    if [ -z "${force:-}" ] && [ -e "$link" ] && ! [ -h "$link" ]; then
        log "will not overwrite normal file: $link"
        continue
    fi
    ln -sfr $vflag $rcfile .bashrc.d/
done

symlink_file liquidpromptrc
