#!/bin/bash
set -eu

branch="$(git branch --show-current)"
set +e
branch_remote="$(git config --local --get branch.${branch}.remote)"
if [ $? -ne 0 ]; then
	echo "NOTICE: Branch doesn't have an upstream configured, using 'origin' as remote" >&2
	branch_remote=origin
fi
set -e
cmd="git push -u $branch_remote $branch"
read -r -p "$cmd ? [y/N]: "
if [ "$REPLY" == "y" ]; then
	$cmd
	exit
fi
